name: Run Lichess Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Display Python version
      run: python --version

    - name: Display installed packages
      run: pip list

    - name: Run bot
      env:
        LICHESS_TOKEN: lip_zam749S1tDrasvs0gFuX
      run: |
        python lichess-bot.py -u
